apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"

rules:
# don't log read actions
- level: None
  verbs: ["get", "watch", "list"]

#log nothing regarding events
- level: None
  resources:
  - group: "" # core
    resources: ["events"]

#log nothing regarding events
- level: Metadata
  resources:
  - group: "" # core
    resources: ["secrets"]

# for everything else log metadata
- level: RequestResponse